name: ci

on:
  push:
    # branches:
    #   - 'master'

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python_version: ["3.9.9", "3.9.8", "3.8.10"]
        precommit_version: ["2.15.0", "2.14.1"]

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        # https://github.com/docker/build-push-action#inputs
        with:
          context: .
          push: false
          tags: iermentraut/pre-commit:${{ matrix.precommit_version }}-python${{ matrix.python_version }}
          build-args: |
            PRECOMMIT_VERSION=${{ matrix.precommit_version }}
            PYTHON_VERSION=${{ matrix.python_version }}

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: iermentraut/phplint:3.0.3
